### ISSUE TITLE
api<19,章节页的那个top菜单不显示

### ISSUE THREAD

**Issue by thom802311** [newbiechen1024/NovelReader#40]
api<19的 仿真翻页 会异常。。
其实是不是不用考虑api<19的机型。

**Comment by newbiechen1024** [comment]
请问会发生什么异常，因为这是个人项目，所以没有进行很好的适配

**Comment by thom802311** [comment]
` FATAL EXCEPTION: main
                                                            java.lang.UnsupportedOperationException
                                                                at android.view.GLES20Canvas.clipPath(GLES20Canvas.java:429)
                                                                at com.ixdzs.tw.widget.animation.SimulationPageAnim.drawCurrentPageArea(SimulationPageAnim.java:487)
                                                                at com.ixdzs.tw.widget.animation.SimulationPageAnim.drawMove(SimulationPageAnim.java:90)
                                                                at com.ixdzs.tw.widget.animation.HorizonPageAnim.draw(HorizonPageAnim.java:177)
                                                                at com.ixdzs.tw.widget.page.PageView.onDraw(PageView.java:207)`

**Comment by thom802311** [comment]
有不支持的方法。我暂时屏蔽掉了
`void setPageMode(PageMode pageMode) {
        mPageMode = pageMode;
        //视图未初始化的时候，禁止调用
        if (mViewWidth == 0 || mViewHeight == 0) return;

        switch (mPageMode) {
            case SIMULATION:
                int version = android.os.Build.VERSION.SDK_INT;
                if (version>=19) {
                    mPageAnim = new SimulationPageAnim(mViewWidth, mViewHeight, this, mPageAnimListener);
                } else {
                    mPageAnim = new CoverPageAnim(mViewWidth, mViewHeight, this, mPageAnimListener);
                }

                break;
            case COVER:
                mPageAnim = new CoverPageAnim(mViewWidth, mViewHeight, this, mPageAnimListener);
                break;
。。。。。。`

**Comment by thom802311** [comment]
![1](https://user-images.githubusercontent.com/34256371/37142897-66e3e0c4-22f4-11e8-83d5-69cbfc9990ee.png)
这个是top菜单不显示

**Comment by thom802311** [comment]
这个翻页的Progress 的max 好像是下一章的 总页数。。

**Comment by newbiechen1024** [comment]
第一个问题，应该是硬件加速的问题。

**Comment by thom802311** [comment]
嗯。布局这个 没找到是哪里影响了，单独弄页面放那个头部布局是能显示的。奇怪。。

**Comment by newbiechen1024** [comment]
头部应该放在 PageView 后面。。。

**Comment by newbiechen1024** [comment]
第三个问题，代码有点逻辑问题，我改下。

**Comment by newbiechen1024** [comment]
基于你的第三个问题，我发现一些地方写的错误，改的地方可能会比较多一点，前两个问题解决了，我先上传一下。。。

**Comment by newbiechen1024** [comment]
改好了。。。

**Comment by thom802311** [comment]
66666，高效～
